#!/usr/bin/env bash
# Script that install and configure HAproxi loadblancer
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
printf "\n\nfrontend smartaleki.tech\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 29538-web-01 	44.200.48.7:80\n\tserver 29538-web-02 18.207.4.238:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
